hmcts/ccd-logstash

Jenkinsfile_CNP, Jenkinsfile_parameterized, packer_images/install_logstash.sh
=> Revert "Added code for supporting multiple product & DB"

packer_images/probate_logstash.conf.in
=> PRO-4904 Use second Date of Death in case matching

packer_images/ccd_jvm.options, variables.tf
=> Up capacity of logstash to 2 and up heap size

packer_images/ccd_logstash.conf.in, packer_images/logstash.yml.in
=> Further modifications to improved logstash

packer_images/logstash.yml.in
=> Revert checkpoint writes change

packer_images/ccd_logstash.conf.in, packer_images/ccdcmc_logstash.conf.in, packer_images/ccddivorce_logstash.conf.in, packer_images/ccdprobate_logstash.conf.in, packer_images/ccdsscs_logstash.conf.in, packer_images/sweeper_logstash.conf.in
=> CHG0034742 - Add in UPPER

Dockerfile, Jenkinsfile_CNP, packer_images/ccdethos_jvm.options, packer_images/ccdethos_logstash.conf.in, variables.tf
=> onboard ETHOS

Jenkinsfile_CNP, Jenkinsfile_parameterized
=> RDM-3541-upgrade_packer

hub.Dockerfile
N/A
Point dockerfile to jursidictions for all service teams.
I have pushed a new latest image.
```
[ ] Yes
[x] No
```
=> fix: point dockerfile to correct configuration

packer_images/ccd_logstash.conf.in, packer_images/ccdcmc_logstash.conf.in, packer_images/ccddivorce_logstash.conf.in, packer_images/ccdethos_logstash.conf.in, packer_images/ccdprobate_logstash.conf.in, packer_images/ccdsscs_logstash.conf.in
https://tools.hmcts.net/jira/browse/RDM-7674
Add last_state_modified_date
```
[ ] Yes
[x] No
```
=> RDM-7674 - Add last_state_modified_date

packer_images/ccd_logstash.conf.in, packer_images/ccdcmc_logstash.conf.in, packer_images/ccddivorce_logstash.conf.in, packer_images/ccdethos_logstash.conf.in, packer_images/ccdprobate_logstash.conf.in, packer_images/ccdsscs_logstash.conf.in
RDM-8747: New fields for supplementary data on CCD and ES case
[RDM-8747] (https://tools.hmcts.net/jira/browse/RDM-8747).
New fields for supplementary data on CCD and ES case
=> Rdm 8747: supplementary data

variables.tf
=> add new vars for dynatrace

main.tf
=> add vars from logstash module

packer_images/sweeper_logstash.conf.in
https://tools.hmcts.net/jira/browse/RDM-8937
Update sweeper configuration in line with others
```
[ ] Yes
[x] No
```
=> RDM-8937 - Update sweeper configuration in line with others

Dockerfile, acr-build.yml, bin/acr-task-creation.sh
Added acr build image config to build individual images for ccd and probate configuration files
=> Added acr build image config 

packer_images/ccd_logstash.conf.in, packer_images/ccdcmc_logstash.conf.in, packer_images/ccddivorce_logstash.conf.in, packer_images/ccdethos_logstash.conf.in, packer_images/ccdprobate_logstash.conf.in, packer_images/ccdsscs_logstash.conf.in, packer_images/sweeper_logstash.conf.in
CCD Release 19.1
```
[ ] Yes
[x] No
```
=> [DO NOT MERGE] CCD Release 19.1

README.md, bin/build-logstash-instances.sh, build-logstash-instances.yml, packer_images/ccdtestall_jvm.options, packer_images/ccdtestall_logstash.conf.in
https://tools.hmcts.net/jira/browse/RDM-10064
Run multiple instances of logstash
```
[ ] Yes
[X ] No
```
=> RDM-10064: Running multiple Logstash with CCD Docker

packer_images/ccd_logstash.conf.in, packer_images/ccdcmc_logstash.conf.in, packer_images/ccddivorce_logstash.conf.in, packer_images/ccdethos_logstash.conf.in, packer_images/ccdprobate_logstash.conf.in, packer_images/ccdsscs_logstash.conf.in, packer_images/ccdtestall_logstash.conf.in, packer_images/sweeper_logstash.conf.in
=> Merge changes from multiple tickets

README.md, acr-build.yml, bin/build-logstash-instances.sh
https://tools.hmcts.net/jira/browse/RDM-10064
Service specific Logstash instance
```
[ ] Yes
[ X] No
```
=> RDM-10064: Updated acr-build.yml to publish service specific images

main.tf, packer_images/sweeper_logstash.conf.in, variables.tf
=> Update 20.2 release cut with latest changes

Jenkinsfile_CNP, Jenkinsfile_parameterized, packer_images/ccd_logstash.conf.in, packer_images/ccdcmc_logstash.conf.in, packer_images/ccddivorce_logstash.conf.in, packer_images/ccdethos_logstash.conf.in, packer_images/ccdprobate_logstash.conf.in, packer_images/ccdsscs_logstash.conf.in, packer_images/ccdtestall_logstash.conf.in, packer_images/logstash.yml.in, packer_images/pipelines.yml, packer_images/sweeper_logstash.conf.in
=> Release Cut 20.2 Revised
